name: Run tests
on: [pull_request]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Setup aglio
      run: |
        python -m pip install -e .[dev]
    - name: Test with pytest
      run: pytest --cov=./ --cov-report=xml:coverage/coverage.xml

    # https://github.com/marketplace/actions/codecov#example-workflowyml-with-codecov-action
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage/
